name: Build and Release k-NN
on:
  push:
    tags:
      - v*

jobs:
  plugin-build-and-ship-artifacts:
    strategy:
      matrix:
        java: [14]

    name: Build and release plugin artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout k-NN
        uses: actions/checkout@v2

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Build and ship plugin artifacts
        run: |
          ./gradlew buildPackages --console=plain -Dbuild.snapshot=false
          artifact=`ls build/distributions/*.zip`
          rpm_artifact=`ls build/distributions/*.rpm`
          deb_artifact=`ls build/distributions/*.deb`


  library-build-and-ship-artifacts:
    name: Build and release JNI library artifacts
    runs-on: ubuntu-latest
    container:
      image: centos:7
    strategy:
      matrix:
        java: [14]
        compiler: [g++]
    steps:
      - name: Checkout k-NN
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Install dependencies
        run: |
          yum update -y
          yum install -y cmake rpm-build gcc-c++ make epel-release unzip
          yum repolist
          yum install -y dpkg
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install
          aws --version

      - name: Build and ship library artifacts
        env:
          CXX: ${{ matrix.compiler }}
        run: |
          cd jni
          sed -i 's/-march=native/-march=x86-64/g' external/nmslib/similarity_search/CMakeLists.txt
          cmake .
          make package

          cd packages
          folder_name=`ls ./*.rpm | sed 's|\(.*\)\..*|\1|'`
          zip_name=$folder_name".zip"
          mkdir $folder_name
          cp ../release/*.so $folder_name
          zip -r $zip_name $folder_name/*
          cd ..

          zip_artifact=`ls packages/*.zip`
          rpm_artifact=`ls packages/*.rpm`
          deb_artifact=`ls packages/*.deb`
